define [
  'static/js/KeyCodes'
], (
  KeyCodes
) ->

  Config = {

    #
    # DEBUG_MODE
    # ----------
    # When set to true, the app will log activity verbosely in the browser console. Can be helpful for debugging.
    # Valid values : true|false
    #
    DEBUG_MODE : false # (true|false)

    #
    # PITCH_TYPE
    # ----------
    # Determines the timbre of the piano keys' sound. Specifically, this string will dictate the shape of the waveform
    # generated by the oscillator nodes for each piano key.
    #
    PITCH_TYPE : 'sine' # (sine|square|sawtooth|triangle)

    #
    # PEDAL_KEY_CODE
    # --------------
    # Specifies the key code that should activate the pedal on key-press. When active, the pedal will sustain pitches
    # for longer, as a real piano pedal would.
    #
    PEDAL_KEY_CODE : KeyCodes.SPACE_BAR # (KeyCodes.*)

    #
    # LABEL_FOR_UNRECOGNIZED_CHORDS
    # -----------------------------
    # The string to display in the UI when a particular key combination does not map to a known chord.
    #
    LABEL_FOR_UNRECOGNIZED_CHORDS : 'Unrecognized Chord' # (any string)

  }

  return Config
