define [
  'static/js/data/KeyCodes'
], (
  KeyCodes
) ->

  #
  # Config
  # ======
  # A set of preferences that will be honored when the app is initialized on page load.
  #
  Config = {

    #
    # DEBUG_MODE
    # ----------
    # When set to true, the app will log activity verbosely in the browser console. Can be helpful for debugging.
    # Valid values : true|false
    #
    DEBUG_MODE : false # (true|false)

    #
    # PITCH_TYPE
    # ----------
    # Determines the timbre of the piano keys' sound. Specifically, this string will dictate the shape of the waveform
    # generated by the oscillator nodes for each piano key.
    #
    PITCH_TYPE : 'square' # (sine|square|sawtooth|triangle)

    #
    # PEDAL_KEY_CODE
    # --------------
    # Specifies the key code that should activate the pedal on key-press. When active, the pedal will sustain pitches
    # for longer, as a real piano pedal would.
    #
    PEDAL_KEY_CODE : KeyCodes.SPACE_BAR # (KeyCodes.*)

    #
    # KEYBOARD_SHIFT_[*]_KEY_CODES
    # ============================
    # Specifies the key codes that on key-press should shift the keyboard downward and upward, respectively, by one
    # piano key.
    #
    KEYBOARD_SHIFT_DOWNWARD_KEY_CODES : [
      KeyCodes.LEFT_ARROW
      KeyCodes.TAB # The keyboard key just to the left of the lowest piano key.
    ]
    KEYBOARD_SHIFT_UPWARD_KEY_CODES : [
      KeyCodes.RIGHT_ARROW
      KeyCodes.BACK_SLASH # The keyboard key just to the right of the highest piano key.
    ]

    #
    # KEYBOARD_SHIFT_THROTTLE_LIMIT_IN_MILLIS
    # =======================================
    # Specifies how frequently the piano keyboard is allowed to shift when either of the KEYBOARD_SHIFT keys defined
    # above is held down by the user.
    #
    KEYBOARD_SHIFT_THROTTLE_LIMIT_IN_MILLIS : 250

    #
    # LOWEST_KEY_OF_DEFAULT_KEYBOARD_RANGE
    # ====================================
    # The lowest key on the keyboard to show on page load (the user will be able to shift the keyboard up or down from
    # here manually).
    #
    LOWEST_KEY_OF_DEFAULT_KEYBOARD_RANGE : 'C' # (A|B|C|D|E|F|G)

    #
    # LABEL_FOR_UNRECOGNIZED_CHORDS
    # -----------------------------
    # The string to display in the UI when a particular key combination does not map to a known chord.
    #
    LABEL_FOR_UNRECOGNIZED_CHORDS : 'Unrecognized Chord' # (any string)

  }

  return Config
